/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.hw4.client;

import java.io.IOException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;


public class App {
    public static void main(String[] args) {
        ArrayList<Thread> threadPool = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            try {
                Client client = new Client("localhost", 12345);
                Thread t = new Thread(new ClientWorker(client.getClientSocket()));
                threadPool.add(t);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        Timestamp startTime = Timestamp.from(Instant.now());
        for (Thread t : threadPool) {
            t.start();
        }

        for (Thread t : threadPool) {
            try {
                t.join();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        Timestamp endTime = Timestamp.from(Instant.now());
        long timeDelta = endTime.getTime() - startTime.getTime();
        long timeDeltaInSeconds = TimeUnit.MILLISECONDS.toSeconds(timeDelta);
        System.out.println("Queries are processed in " + timeDelta + " milliseconds");
    }
}
