/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.hw4.server;

import java.io.IOException;
import java.net.Socket;
import java.sql.SQLException;


public class App {
    public static void main(String[] args) {
        try {
//            JDBCManager jdbcManager = new JDBCManager("localhost", "5432", "ece568_hw4", "postgres", "postgres");
            JDBCManager jdbcManager = new JDBCManager("db", "5432", "postgres", "postgres", "P@ssw0rd!");
            jdbcManager.deleteAll();
            jdbcManager.getConnection().close();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        try {
            Server server = new Server(12345);
            while (true) {
                Socket clientSocket = server.acceptConnection();
                Thread t = new Thread(new ServerWorker(clientSocket));
                t.start();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}